# Site settings
title: Christian Wilkie's Home Page
email: christianwilkie@gmail.com
description: > # this means to ignore newlines until "baseurl:"
#optional description
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://christianwilkie.github.io/" # the base hostname & protocol for your site
twitter_username: WilkieChristian
github_username:  ChristianWilkie

# Build settings
markdown: kramdown
